"---"
mergeable:
  pull_requests:
    label:
      and:
        - must_exclude:
            regex: '^disposition/DO NOT MERGE'
            message: 'Pull request marked not mergeable'
        - or:
          - and:
            - must_include:
                regex: '^release notes: yes'
                message: 'Please add the label (release notes: yes)'
            - must_include:
                regex: '^lang\/'
                message: 'Please add a language label (lang/...)'
          - must_include:
              regex: '^release notes: no'
<<<<<<< HEAD
              message: 'Please add the label (release notes: no)'
=======
              message: 'Please add the label (release notes: no)'
>>>>>>> d9ed764d1d0c10fd3e28b74802d13f05f4906e0a
